# Generated by Django 3.0.7 on 2020-08-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subImage',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
