# Generated by Django 3.0.7 on 2020-08-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_subimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='adviceImage',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
    ]
